[workspace]
members = [
    "flumox",
    "flumox-server",
    "flumox-game-tracker",
    "flumox-seed-maker",
    "time-expr",
    "channel-map", "http-forwarded-header",
]
resolver = "2"

[profile.release]
lto = "fat"
